//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icxjubroqtunzeyzpomfksahgw
        ///ibxjvbroqtunleyzjdmfksahow
        ///icxjvbroqtinleyzpdmflsahnw
        ///icxjvbnoqtunleyvpgmfksahgw
        ///wcxjvbroqrunleyzpdmfksahge
        ///icxjtbroqtjzleyzpdmfksahgw
        ///icxjvbrohtunleyzpdmfkbahsw
        ///xcxjvbroqcunleyzpdmfksaxgw
        ///ycxjvbroqtunleyzpowfksahgw
        ///icxfvbroqtunleyzpdmfksncgw
        ///ixxjvbuoqtunleyzpdvfksahgw
        ///icfjvbroqtunleyzpdmfksadgt
        ///icxjvbroqdunleyzpdafksqhgw
        ///icxjvbrobtunlelzpdmfkuahgs
        ///ujxjvbroqtunleyzpdmqksahgw
        ///icqjvsroqtunleyzpdmfksahuw
        ///icxjvbroptpnleyzpdmfksangw
        ///ipxjvbroqtunleyzpdmfesahgi
        ///icajvbro [rest of string was truncated]&quot;;.
        /// </summary>
        public static string day2 {
            get {
                return ResourceManager.GetString("day2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1
        ///-7
        ///-5
        ///-16
        ///-2
        ///-11
        ///-17
        ///+14
        ///-8
        ///-5
        ///-7
        ///+8
        ///+1
        ///+13
        ///+6
        ///+7
        ///+15
        ///-5
        ///+15
        ///-16
        ///-1
        ///-16
        ///+19
        ///-6
        ///-19
        ///-2
        ///+6
        ///+16
        ///-11
        ///-19
        ///-17
        ///-8
        ///-5
        ///+8
        ///-10
        ///-5
        ///+10
        ///-13
        ///-4
        ///+5
        ///+18
        ///+8
        ///-18
        ///-4
        ///-6
        ///-14
        ///-5
        ///+8
        ///+5
        ///-18
        ///+6
        ///-7
        ///-12
        ///-5
        ///-1
        ///+16
        ///-19
        ///-2
        ///-13
        ///+4
        ///-5
        ///+2
        ///+2
        ///-10
        ///+17
        ///-1
        ///+17
        ///-5
        ///+9
        ///-10
        ///+12
        ///+20
        ///+17
        ///-12
        ///+9
        ///+16
        ///+14
        ///-20
        ///+3
        ///+15
        ///-2
        ///+12
        ///+1
        ///+17
        ///-13
        ///-2
        ///-6
        ///-8
        ///-3
        ///+18
        ///+21
        ///+11
        ///-20
        ///+18
        ///+7
        ///+19
        ///+17
        ///+17
        ///-15
        ///-8
        ///+19
        ///+1
        ///+9
        ///+11
        ///-15
        ///+19
        ///-14
        ///-2
        ///-17
        ///+11
        ///+16
        ///+14
        ///+16
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input_Day1 {
            get {
                return ResourceManager.GetString("Input_Day1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icxjubroqtunzeyzpomfksahgw
        ///ibxjvbroqtunleyzjdmfksahow
        ///icxjvbroqtinleyzpdmflsahnw
        ///icxjvbnoqtunleyvpgmfksahgw
        ///wcxjvbroqrunleyzpdmfksahge
        ///icxjtbroqtjzleyzpdmfksahgw
        ///icxjvbrohtunleyzpdmfkbahsw
        ///xcxjvbroqcunleyzpdmfksaxgw
        ///ycxjvbroqtunleyzpowfksahgw
        ///icxfvbroqtunleyzpdmfksncgw
        ///ixxjvbuoqtunleyzpdvfksahgw
        ///icfjvbroqtunleyzpdmfksadgt
        ///icxjvbroqdunleyzpdafksqhgw
        ///icxjvbrobtunlelzpdmfkuahgs
        ///ujxjvbroqtunleyzpdmqksahgw
        ///icqjvsroqtunleyzpdmfksahuw
        ///icxjvbroptpnleyzpdmfksangw
        ///ipxjvbroqtunleyzpdmfesahgi
        ///icajvbro [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input_Day2 {
            get {
                return ResourceManager.GetString("Input_Day2", resourceCulture);
            }
        }
    }
}
