//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -1
        ///-7
        ///-5
        ///-16
        ///-2
        ///-11
        ///-17
        ///+14
        ///-8
        ///-5
        ///-7
        ///+8
        ///+1
        ///+13
        ///+6
        ///+7
        ///+15
        ///-5
        ///+15
        ///-16
        ///-1
        ///-16
        ///+19
        ///-6
        ///-19
        ///-2
        ///+6
        ///+16
        ///-11
        ///-19
        ///-17
        ///-8
        ///-5
        ///+8
        ///-10
        ///-5
        ///+10
        ///-13
        ///-4
        ///+5
        ///+18
        ///+8
        ///-18
        ///-4
        ///-6
        ///-14
        ///-5
        ///+8
        ///+5
        ///-18
        ///+6
        ///-7
        ///-12
        ///-5
        ///-1
        ///+16
        ///-19
        ///-2
        ///-13
        ///+4
        ///-5
        ///+2
        ///+2
        ///-10
        ///+17
        ///-1
        ///+17
        ///-5
        ///+9
        ///-10
        ///+12
        ///+20
        ///+17
        ///-12
        ///+9
        ///+16
        ///+14
        ///-20
        ///+3
        ///+15
        ///-2
        ///+12
        ///+1
        ///+17
        ///-13
        ///-2
        ///-6
        ///-8
        ///-3
        ///+18
        ///+21
        ///+11
        ///-20
        ///+18
        ///+7
        ///+19
        ///+17
        ///+17
        ///-15
        ///-8
        ///+19
        ///+1
        ///+9
        ///+11
        ///-15
        ///+19
        ///-14
        ///-2
        ///-17
        ///+11
        ///+16
        ///+14
        ///+16
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input_Day01 {
            get {
                return ResourceManager.GetString("Input_Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icxjubroqtunzeyzpomfksahgw
        ///ibxjvbroqtunleyzjdmfksahow
        ///icxjvbroqtinleyzpdmflsahnw
        ///icxjvbnoqtunleyvpgmfksahgw
        ///wcxjvbroqrunleyzpdmfksahge
        ///icxjtbroqtjzleyzpdmfksahgw
        ///icxjvbrohtunleyzpdmfkbahsw
        ///xcxjvbroqcunleyzpdmfksaxgw
        ///ycxjvbroqtunleyzpowfksahgw
        ///icxfvbroqtunleyzpdmfksncgw
        ///ixxjvbuoqtunleyzpdvfksahgw
        ///icfjvbroqtunleyzpdmfksadgt
        ///icxjvbroqdunleyzpdafksqhgw
        ///icxjvbrobtunlelzpdmfkuahgs
        ///ujxjvbroqtunleyzpdmqksahgw
        ///icqjvsroqtunleyzpdmfksahuw
        ///icxjvbroptpnleyzpdmfksangw
        ///ipxjvbroqtunleyzpdmfesahgi
        ///icajvbro [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input_Day02 {
            get {
                return ResourceManager.GetString("Input_Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #1 @ 661,227: 29x11
        ///#2 @ 391,45: 27x20
        ///#3 @ 467,241: 23x12
        ///#4 @ 120,334: 18x28
        ///#5 @ 671,406: 28x16
        ///#6 @ 422,790: 23x12
        ///#7 @ 321,868: 13x17
        ///#8 @ 509,931: 11x20
        ///#9 @ 362,833: 26x20
        ///#10 @ 968,503: 27x16
        ///#11 @ 479,146: 26x25
        ///#12 @ 269,129: 25x14
        ///#13 @ 78,880: 25x17
        ///#14 @ 141,545: 11x16
        ///#15 @ 765,139: 21x29
        ///#16 @ 609,202: 13x16
        ///#17 @ 582,471: 22x21
        ///#18 @ 587,65: 10x17
        ///#19 @ 979,416: 18x23
        ///#20 @ 904,488: 16x26
        ///#21 @ 601,930: 12x23
        ///#22 @ 561,647: 24x26
        ///#23 @ 814,263: 18x27
        ///#24 @ 576,362: 20x [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input_Day03 {
            get {
                return ResourceManager.GetString("Input_Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1518-03-19 00:02] Guard #647 begins shift
        ///[1518-03-23 00:04] Guard #2267 begins shift
        ///[1518-11-04 00:24] falls asleep
        ///[1518-09-17 00:04] Guard #509 begins shift
        ///[1518-09-24 00:30] falls asleep
        ///[1518-09-11 00:13] falls asleep
        ///[1518-05-24 00:29] falls asleep
        ///[1518-04-23 00:03] Guard #647 begins shift
        ///[1518-03-02 00:56] falls asleep
        ///[1518-06-03 00:17] falls asleep
        ///[1518-05-07 00:26] wakes up
        ///[1518-09-01 00:30] falls asleep
        ///[1518-03-22 00:52] falls asleep
        ///[1518-03-28 00:04] Guard #2011 begins shif [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input_Day04 {
            get {
                return ResourceManager.GetString("Input_Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LlspxXPjJMmBbVvyYNnzLlZFfSTtULRlLrTtbBlaAJjqQUuXxQnWwNqIiDiIdRIWwQqirWQqwfFlLiIeYyEJiIjjPHhpStTsJVTtvtjbBjuUJJZUuZzGgOoHhUumMYyoOBboVHZzhvsKkSspPZzFfTtScCOzkKfUxXLluLlRrFTyYSstuUJVvLljJjTqQCxXjJxVvCcwWVvXzJjyFfYleEUuAORroamMLRMmOorKkSNnsXxvVJjZOohHeELGglVGkKJjgvciIMeEvQqVmVvHgGKkhwWdDMmwbBrRrRWjrRJSCcoOPpkKepPjJEswaAfFVvWwfFpnNoDdOPpqVvFfHJJjjzZCmMvwWXxJjzkmMKZQqPzyYZHhKkAFfapgOoBbFAVvatTfGCyYTtcgGLlEerRFHhfIbVvBbBiFfNSsnDDddNnnfFjJtjJkKRrTNRxTtXTtQqRTtnfFNAarRrqQIjJiuUsSgZGglLzYiIyGiIGgcxXCrrRRrVEyYtTzlLZe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input_Day05 {
            get {
                return ResourceManager.GetString("Input_Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 305, 349
        ///315, 193
        ///154, 62
        ///246, 310
        ///145, 283
        ///260, 324
        ///342, 79
        ///321, 353
        ///40, 242
        ///351, 353
        ///337, 297
        ///174, 194
        ///251, 160
        ///314, 195
        ///114, 81
        ///204, 246
        ///203, 169
        ///203, 296
        ///60, 276
        ///201, 47
        ///206, 96
        ///243, 46
        ///295, 304
        ///319, 80
        ///213, 330
        ///337, 255
        ///40, 262
        ///302, 150
        ///147, 349
        ///317, 240
        ///96, 315
        ///133, 305
        ///320, 348
        ///210, 300
        ///266, 216
        ///223, 319
        ///207, 152
        ///127, 214
        ///312, 245
        ///49, 329
        ///211, 84
        ///129, 276
        ///247, 143
        ///208, 235
        ///271, 126
        ///124, 211
        ///144, 184
        ///54, 88
        ///354, 300
        ///148, 85
        ///.
        /// </summary>
        public static string Input_Day06 {
            get {
                return ResourceManager.GetString("Input_Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step F must be finished before step N can begin.
        ///Step V must be finished before step Y can begin.
        ///Step B must be finished before step W can begin.
        ///Step K must be finished before step O can begin.
        ///Step E must be finished before step H can begin.
        ///Step A must be finished before step P can begin.
        ///Step Y must be finished before step S can begin.
        ///Step T must be finished before step L can begin.
        ///Step G must be finished before step R can begin.
        ///Step I must be finished before step H can begin.
        ///Step X must  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input_Day07 {
            get {
                return ResourceManager.GetString("Input_Day07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 11 6 2 5 4 3 4 1 8 0 6 8 3 1 3 1 8 1 3 1 3 2 3 1 2 1 9 0 9 2 5 6 1 6 4 2 9 1 2 3 2 2 1 3 1 3 1 1 8 0 9 9 6 5 6 8 3 2 1 5 2 1 1 1 1 2 1 1 1 4 5 2 3 4 1 9 0 9 6 1 4 6 1 2 8 8 5 1 1 2 1 1 1 3 1 2 1 7 0 11 2 7 5 1 1 1 1 9 5 4 8 1 1 3 2 2 2 2 1 6 0 9 1 8 8 6 9 9 7 1 1 3 1 2 2 1 1 3 3 1 3 3 7 1 8 0 7 1 8 5 7 4 1 1 2 1 1 3 3 1 2 2 1 6 0 11 3 7 5 9 3 1 8 9 8 1 1 1 1 2 1 2 1 1 9 0 6 1 3 7 4 1 6 1 1 3 1 1 3 2 1 1 1 1 1 5 3 3 1 3 6 1 8 0 6 2 5 6 1 6 3 2 1 1 3 3 1 2 3 1 7 0 9 6 3 6 4 1 5 4 3 9 1 1 1 3 2 1 3 1 5 0 10  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input_Day08 {
            get {
                return ResourceManager.GetString("Input_Day08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 468 players; last marble is worth 71010 points
        ///.
        /// </summary>
        public static string Input_Day09 {
            get {
                return ResourceManager.GetString("Input_Day09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to position=&lt;-20515,  20790&gt; velocity=&lt; 2, -2&gt;
        ///position=&lt; 10476,  31130&gt; velocity=&lt;-1, -3&gt;
        ///position=&lt; 51833,  41457&gt; velocity=&lt;-5, -4&gt;
        ///position=&lt; 51808, -30871&gt; velocity=&lt;-5,  3&gt;
        ///position=&lt; 20845,  41465&gt; velocity=&lt;-2, -4&gt;
        ///position=&lt;-30848, -10200&gt; velocity=&lt; 3,  1&gt;
        ///position=&lt; 31159, -20533&gt; velocity=&lt;-3,  2&gt;
        ///position=&lt; 10497,  41464&gt; velocity=&lt;-1, -4&gt;
        ///position=&lt;-51511, -10200&gt; velocity=&lt; 5,  1&gt;
        ///position=&lt;-41170, -20542&gt; velocity=&lt; 4,  2&gt;
        ///position=&lt; 10463, -41204&gt; velocity=&lt;-1,  4&gt;
        ///position=&lt;-30867, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Input_Day10 {
            get {
                return ResourceManager.GetString("Input_Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5535
        ///.
        /// </summary>
        public static string Input_Day11 {
            get {
                return ResourceManager.GetString("Input_Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day12 {
            get {
                return ResourceManager.GetString("Input_Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day13 {
            get {
                return ResourceManager.GetString("Input_Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day14 {
            get {
                return ResourceManager.GetString("Input_Day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day15 {
            get {
                return ResourceManager.GetString("Input_Day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day16 {
            get {
                return ResourceManager.GetString("Input_Day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day17 {
            get {
                return ResourceManager.GetString("Input_Day17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day18 {
            get {
                return ResourceManager.GetString("Input_Day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day19 {
            get {
                return ResourceManager.GetString("Input_Day19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day20 {
            get {
                return ResourceManager.GetString("Input_Day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day21 {
            get {
                return ResourceManager.GetString("Input_Day21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day22 {
            get {
                return ResourceManager.GetString("Input_Day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day23 {
            get {
                return ResourceManager.GetString("Input_Day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day24 {
            get {
                return ResourceManager.GetString("Input_Day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Input_Day25 {
            get {
                return ResourceManager.GetString("Input_Day25", resourceCulture);
            }
        }
    }
}
